spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab-java-add-and-update?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

spring-doc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

server:
  error:
    include-message: always
    include-binding-errors: always
